spring:
  application:
    name: Greet-service
  boot:
    admin:
      client:
        url: http://localhost:1111/

server:
  port: 9090

management:
  endpoints:
    web:
      exposure:
        include: '*'