spring:
  application:
    name: Welcome-Service
  boot:               # Admin server configuration
    admin:
      client:
        url: http://localhost:1111/

#server:
#  port: 8081

# To manually register service with service registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# Configure actuator endpoint
management:
  endpoints:
    web:
      exposure:
        include: '*'
